spring:
  application:
    name: general_service

  # Database Configuration - NeonDB (PostgreSQL Cloud)
  datasource:
    url: jdbc:postgresql://ep-shy-hall-adchttnv-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require
    username: neondb_owner
    password: npg_CAmuOv5L4gSG
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 20000

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  # RabbitMQ Configuration
  rabbitmq:
    host: localhost
    port: 5672

  # Jackson Configuration
  jackson:
    serialization:
      indent_output: true
    property-naming-strategy: SNAKE_CASE

# Logging Configuration
logging:
  level:
    com.example.base: DEBUG
    org.springframework.amqp: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
